metanorma/mn-native-pdf

- Makefile
- xslt_src/itu.recommendation.core.xsl
- xslt_src/ogc.other.core.xsl
> WIP: Enable unsupported ITU files

- xslt_src/common.xsl
Reverts metanorma/mn-native-pdf#128
> Revert "Common xslt update for NIST"

- .gitmodules
- Makefile
- xslt_src/common.xsl
- xslt_src/m3d.report.core.xsl
For @Intelligent2013 .
Sample documents available:
* https://www.m3aawg.org/sites/default/files/m3aawg-dns-crypto-recipes-2018-09.pdf
* https://www.m3aawg.org/sites/default/files/m3aawg-mobile-messaging-bcp-political-programs-us-2020-04.pdf
> Add M3AAWG samples for XSL creation

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/gb.recommendation.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/m3aawg.report.core.xsl
- xslt_src/mpfa.standards.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/ribose.standard.core.xsl
- xslt_src/un.plenary.core.xsl
- xslt_src/un.recommendation.core.xsl
> Add figures and tables ToC 

- Makefile
- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/m3aawg.report.core.xsl
- xslt_src/mpfa.standards.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/ribose.standard.core.xsl
- xslt_src/un.plenary.core.xsl
- xslt_src/un.recommendation.core.xsl
> Table autolayout

- xslt_src/common.xsl
> common.xslt updated for  #369

- xslt_src/common.xsl
> common.xslt updated for /metanorma/metanorma-ogc#386

- xslt_src/common.xsl
> common.xslt updated for BIPM, metanorma/metanorma-bipm#178

- xslt_src/common.xsl
- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for metanorma/metanorma-ieee#57

- xslt_src/common.xsl
- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for metanorma/metanorma-ieee#26

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for stage processing, metanorma/metanorma-ieee#82

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for empty document, metanorma/metanorma-ieee#84

- .github/workflows/debian.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
> #367 create PR for metanorma-* instead commit to default branch

- xslt_src/bipm.brochure.core.xsl
> BIPM xslt updated for empty bibliography, metanorma/bipm-si-brochure#182

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for approved date, metanorma/metanorma-ieee#92

- xslt_src/common.xsl
- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for metanorma/metanorma-ieee#110

- .github/workflows/ubuntu.yml
This PR implements automatic PR aggregation #402.
After each run, it will update the list of active PRs in the top comment. @ronaldtse @opoudjis as far as I understand it will be useful
Let me know if I can do anything else to improve this process
> Maintain list of opened PRs in #402 issue

- xslt_src/common.xsl
> common.xslt updated for styles processing, #401

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for FD Amendment layout, metanorma/metanorma-iso#758

- xslt_src/common.xsl
> common.xsl updated for Requirements styles, metanorma/metanorma-iso#778

- xslt_src/common.xsl
> Wrong multiplier fixed, metanorma/metanorma-iso#713 and #365

- xslt_src/itu.recommendation.core.xsl
> ITU xslt updated for #420

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Bipm update

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> Xslt update

- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for metanorma/metanorma-iso#827

- Makefile
- xslt_src/ogc.draft-standard.core.xsl
> ogc.draft-standard.core.xsl added for metanorma/metanorma-ogc#445

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Asciimath support

- xslt_src/iso.international-standard.core.xsl
> Iso update

- xslt_src/common.xsl
> common.xslt updated for metanorma/metanorma-iso#848

- xslt_src/ieee.standard.core.xsl
> Ieee update

- xslt_src/common.xsl
- xslt_src/iho.standard.core.xsl
> Iho update

- xslt_src/common.xsl
> XSLT updated for strip spaces in xref, metanorma/metanorma-iso#852

- xslt_src/common.xsl
> common.xslt updated for SVG rgba support, metanorma/metanorma-ieee#163

- xslt_src/common.xsl
> common.xslt updated for keep numbers within line, #353

- xslt_src/common.xsl
> common.xslt updated for #463

- xslt_src/common.xsl
> Iso table issue fix

- xslt_src/common.xsl
> common.xsl updated for ISO, sourcecode font-size fixed

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Bipm optimize

- xslt_src/common.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/ogc.standard.core.xsl
> Bibitem refactoring

- Makefile
- xslt_src/common.xsl
> Sourcecode highlight

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> common.xsl and ISO xsl updated for fixing #470

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/gb.recommendation.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/m3aawg.report.core.xsl
- xslt_src/mpfa.standards.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/ribose.standard.core.xsl
- xslt_src/un.plenary.core.xsl
- xslt_src/un.recommendation.core.xsl
> XSLT updated for fn in table, figure name, metanorma/metanorma-un#122

- xslt_src/common.xsl
- xslt_src/un.plenary.core.xsl
- xslt_src/un.recommendation.core.xsl
> XSLT UN update

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for preprocessing xslt feature, metanorma/mn2pdf#169

- xslt_src/common.xsl
> Sourcecode linenumbers

- xslt_src/common.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
> Table array

- xslt_src/common.xsl
> xslt updated, misc-container replaced with metanorma-extension, #482

- xslt_src/common.xsl
- xslt_src/itu.recommendation.core.xsl
> ITU issues fixing

- xslt_src/itu.recommendation.core.xsl
> ITU XSLT, workaround for summary removed, metanorma/metanorma-itu#373

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> BIPM termexample and termnote fix

- xslt_src/common.xsl
> BSI 1234 update

- xslt_src/common.xsl
> Bsi xslt update

- xslt_src/common.xsl
> common.xslt updated for metanorma/mn-samples-bsi#246

- xslt_src/jcgm.standard.core.xsl
> JCGM xslt updated for #505 and metanorma/metanorma-cli#300

- xslt_src/common.xsl
> common.xslt updated for email in table, metanorma/metanorma-itu#402

- xslt_src/iec.international-standard.core.xsl
> IEC xslt updated for price code, metanorma/metanorma-iec#196

- xslt_src/common.xsl
> common.xslt updated for missing target in callout

- xslt_src/common.xsl
> common.xslt updated for annotation, metanorma/metanorma-ogc#517

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> Jis update

- xslt_src/common.xsl
> common.xslt updated for table in ToC issue, metanorma/metanorma-ogc#524

- xslt_src/common.xsl
> IEC XSLT update

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for dl styles, metanorma/metanorma-ogc#523

- xslt_src/common.xsl
> sourcecode dl

- xslt_src/common.xsl
> common.xslt updated for dl in sourcecode fontsize

- xslt_src/common.xsl
> common.xslt updated, div processing added, #537

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
> fo:basic-link fix

- Makefile
- xslt_src/common.xsl
> XSLT update for external image path prefix

- xslt_src/common.xsl
> common.xsl updated for metanorma/iso-iec-80000#38

- xslt_src/common.xsl
> common.xsl updated for metanorma/metanorma-standoc#777

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Toc update

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Mathml mo update

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for ToC clause, metanorma/metanorma-jis#13

- xslt_src/common.xsl
- xslt_src/iec.international-standard.core.xsl
> IEC xslt updated for preface elements, metanorma/metanorma-iec#236

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> BIPM XSLT update

- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for clause toc, metanorma/metanorma-iso#988

- xslt_src/common.xsl
> common.xsl updated for ISO dl space, metanorma/metanorma-iso#990

- xslt_src/common.xsl
> XSLT JIS update

- xslt_src/common.xsl
> XSLT refactored

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> JIS xslt update

- xslt_src/common.xsl
metanorma/metanorma-ribose#210
> common.xsl updated for xref keep within line

- .github/workflows/debian.yml
- .github/workflows/ubuntu.yml
> .yml updated for metanorma/metanorma#293

- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated, added line numbers feature

- xslt_src/common.xsl
> common.xsl updated, toc removed from bookmarks, #585

- Makefile
- xslt_src/common.xsl
> Table FO to IF performance

- xslt_src/iec.international-standard.core.xsl
> IEC XSLT updated for docidentifier, metanorma/metanorma-iec#154

- Makefile
- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> Tags tree update

- xslt_src/common.xsl
> common xslt updated for mathml rendering fix, metanorma/mn2pdf#221

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for note tags tree, metanorma/metanorma-iso#1003

- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
> XSLT update for I18n strings

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for contributors names, metanorma/metanorma-jis#14

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> XSLT updated for table continued text, #599

- xslt_src/common.xsl
- xslt_src/jcgm.standard.core.xsl
> JCGM xslt updated for title type, metanorma/metanorma-bipm#340

- xslt_src/common.xsl
> common.xslt updated for image width height processing

- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for metanorma/metanorma-ogc#581

- Makefile
> insecure mode removed, #598

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for cover page text, metanorma/metanorma-jis#64

- xslt_src/common.xsl
> common.xslt updated for additional fonts priority, #612

- xslt_src/itu.recommendation.core.xsl
> ITU XSLT update

- xslt_src/itu.recommendation.core.xsl
> ITU xslt updated for metanorma/metanorma-itu#468

- xslt_src/ogc.standard.core.xsl
> OGC XSLT update

- xslt_src/common.xsl
> common.xsl updated for font-size support, #622

- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for metanorma/metanorma-iso#1048

- xslt_src/ieee.standard.core.xsl
> IEEE XSLT update

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for ICAP whitepaper, metanorma/metanorma-ieee#312

- xslt_src/jis.international-standard.core.xsl
> JIS XSLT updated for textual date, metanorma/metanorma-jis#12

- xslt_src/common.xsl
> common.xsl updated for metanorma/metanorma-standoc#844

- xslt_src/jis.international-standard.core.xsl
> JIS XSLT updated for boilerplate, metanorma/metanorma-jis#9

- .github/workflows/debian.yml
- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
> ubuntu.yml updated for ruby 3.1, lutaml/expressir#143

- xslt_src/jis.international-standard.core.xsl
> JIS XSLT fixed for prevent empty elements, metanorma/metanorma-jis#15

- xslt_src/iso.international-standard.core.xsl
> ISO XSLT update for fast track

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for retired status, metanorma/metanorma-ogc#622

- xslt_src/common.xsl
> BSI XSLT change tags

- xslt_src/iso.international-standard.core.xsl
> Iso layout 2024

- xslt_src/common.xsl
> common.xsl update for fixing issue metanorma/metanorma-ogc#629

- xslt_src/common.xsl
metanorma/metanorma-iec#153, metanorma/metanorma-iec#157
> common.xsl updated for span without formatting

- Makefile
- xslt_src/iec.international-standard.core.xsl
> Iec edition

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> Iso historical

- xslt_src/itu.recommendation.core.xsl
> Itu new coverpage

- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
> OGC xslt updated for 'editors' resource, metanorma/isodoc#400

- xslt_src/common.xsl
> common.xsl updated for text in smallcap, metanorma/metanorma-iso#1115

- xslt_src/itu.recommendation.core.xsl
> ITU xslt updated, debug info removed, metanorma/metanorma-itu#474

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> ISO layout 2024 update

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> Table autolayout refactoring

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> images resize updated, #669

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for inline image scale, metanorma/metanorma-ogc#656

- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for fo:character, #672

- xslt_src/iso.international-standard.core.xsl
> Iso coverpage fix

- xslt_src/iso.international-standard.core.xsl
> ISO xslt updated for fixing table width issue, metanorma/metanorma#385

- xslt_src/common.xsl
> table width algorithm performance optimization, metanorma/mn2pdf#245

- xslt_src/common.xsl
- xslt_src/plateau.international-standard.core.xsl
> plateau xslt updated ul list label, metanorma/metanorma-plateau#2

- xslt_src/common.xsl
> image scaling issue fixing, metanorma/metanorma-plateau#19

- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for pagebreak issue, metanorma/metanorma-ogc#674

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/m3aawg.report.core.xsl
- xslt_src/mpfa.standards.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/ribose.standard.core.xsl
- xslt_src/un.plenary.core.xsl
- xslt_src/un.recommendation.core.xsl
> keep-with-next attribute added, #686

- xslt_src/un.plenary.core.xsl
> UN xslt updated for fixing #645

- xslt_src/common.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/plateau.international-standard.core.xsl
> plateau and itu xslt updated for #676

- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> ISO and CSD xslt refactored for landscape pages, #449

- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
> CSA xslt refactored for landscape pages, #449

- xslt_src/iec.international-standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
> Xslt refactoring

- xslt_src/common.xsl
- xslt_src/plateau.international-standard.core.xsl
> Plateau update

- xslt_src/common.xsl
> common.xsl fixing empty ratio, #449

- xslt_src/common.xsl
- xslt_src/ogc.white-paper.core.xsl
> OGC white-paper xslt refactored for landscape pages, #449

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC standard xslt refactored for landscape pages, #449

- xslt_src/common.xsl
- xslt_src/plateau.international-standard.core.xsl
> Plateau xslt refactored for landscape pages, #449

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for metanorma/mn-samples-jis#30

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for dl footnotes, metanorma/metanorma-jis#192

- xslt_src/common.xsl
> common.xsl updated for PDF attachments, metanorma/metanorma-standoc#900

- xslt_src/common.xsl
> common.xsl, error fix, metanorma/metanorma-standoc#900

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
> OGX xslt updated for colors, metanorma/metanorma-ogc#698

- xslt_src/plateau.international-standard.core.xsl
> Plateau xslt updated for metanorma/mn-samples-plateau#168

- xslt_src/common.xsl
> common xslt updated for attachments, metanorma/metanorma#407

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for metanorma/mn-samples-plateau#168

- xslt_src/common.xsl
> common.xsl updated for attachment description, #739

- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for ToC, metanorma/metanorma-ogc#715

- .github/workflows/ubuntu.yml
- .github/workflows/verapdfcheck.yml
- Makefile
- xslt_src/common.xsl
> verapdfcheck.yml added for metanorma/mn2pdf#265

- Makefile
- xslt_src/common.xsl
> Fileattachment annotation

- .github/workflows/verapdfcheck.yml
- Makefile
- xslt_src/common.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
> verapdfcheck.yml updated for PDF/UA-1, metanorma/mn2pdf#287

- xslt_src/common.xsl
> common.xsl updated for H levels, metanorma/mn2pdf#289

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> JIS vertical layout

- xslt_src/plateau.international-standard.core.xsl
> Plateau xslt updated for ToC issue, metanorma/metanorma-plateau#120

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> Update for Presentation XML

- xslt_src/common.xsl
- xslt_src/itu.recommendation.core.xsl
> Update Presentation XML (part2)

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Update pres xml part3

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> MathML linebreak

- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for ToC item indent, metanorma/metanorma-jis#226

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/jis.international-standard.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/plateau.international-standard.core.xsl
- xslt_src/ribose.standard.core.xsl
> common.xsl updated for new title and name format, #770

- xslt_src/iso.international-standard.core.xsl
metanorma/metanorma-iso#1246, metanorma/metanorma-iso#1251
> ISO xslt updated for docidentifier and French title for PRF

- xslt_src/common.xsl
> common.xsl updated for BIPM title, metanorma/bipm-si-brochure#263

- xslt_src/common.xsl
> common.xslt updated for http link, metanorma/bipm-si-brochure#271

- xslt_src/cc.standard.core.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/plateau.international-standard.core.xsl
- xslt_src/ribose.standard.core.xsl
> xslt updated for fixing page-sequence issue, metanorma/mn2pdf#314

- xslt_src/iso.international-standard.core.xsl
> ISO CEN parallel

- xslt_src/bipm.brochure.core.xsl
> BIPM xslt updated for version rendering, metanorma/bipm-si-brochure#282

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for collection support, metanorma/mn-samples-jis#68

- xslt_src/common.xsl
> common.xsl updated strike formatting, metanorma/mn2pdf#318

- xslt_src/common.xsl
- xslt_src/itu.recommendation.core.xsl
> ITU XSLT collection support

- xslt_src/itu.recommendation.core.xsl
> ITU xslt fixed for ToC in collection, metanorma/metanorma-itu#605

- xslt_src/common.xsl
- xslt_src/jis.international-standard.core.xsl
> JIS xslt updated for footnotes, metanorma/laozi#7

- xslt_src/common.xsl
- xslt_src/itu.recommendation.core.xsl
> ITU bibliography table

- Makefile
- xslt_src/jis.international-standard.core.xsl
> JIS update for surrogate pair

- xslt_src/common.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/ogc.standard.core.xsl
> Update XSLT for terms in new presentation XML

- xslt_src/jis.international-standard.core.xsl
- xslt_src/plateau.international-standard.core.xsl
> Plateau and JIS xslt updated for metanorma/mn-samples-plateau#323

- xslt_src/common.xsl
- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for requirement name, metanorma/mn-requirements#37

- xslt_src/common.xsl
> common.xsl updated for #812

- xslt_src/common.xsl
> namespace checking temporarily disabled, #814

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/jis.international-standard.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/plateau.international-standard.core.xsl
- xslt_src/ribose.standard.core.xsl
> Update root tag

- xslt_src/plateau.international-standard.core.xsl
> Plateau xslt updated for metanorma/mn-samples-plateau#349

- xslt_src/common.xsl
- xslt_src/plateau.international-standard.core.xsl
> Update Plateau for tfoot

- xslt_src/common.xsl
- xslt_src/plateau.international-standard.core.xsl
> Plateau xslt updated, metanorma/metanorma-plateau#171

- Makefile
- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/common.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iec.international-standard.core.xsl
- xslt_src/ieee.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/iso.international-standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/jcgm.standard.core.xsl
- xslt_src/jis.international-standard.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
- xslt_src/plateau.international-standard.core.xsl
- xslt_src/ribose.standard.core.xsl
> Update pres xml footnotes

- xslt_src/common.xsl
> common.xsl updated for Plateau ul labels, metanorma/isodoc#653

- xslt_src/bipm.brochure.core.xsl
> BIPM xslt refactored for fn labels, metanorma/isodoc#658

- .gitmodules
- .gitmodules.copy
- Makefile
- xslt_src/common.xsl
> Update pres xml reviews

- xslt_src/common.xsl
> common.xsl optimized for metanorma/iso-2533#40

- xslt_src/bipm.brochure.core.xsl
> BIPM xslt updated for repeated fn, metanorma/isodoc#658

- Makefile
- xslt_src/common.xsl
> Table tags

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
> Update pres xml list

- xslt_src/iho.standard.core.xsl
> IHO coverpage

- xslt_src/common.xsl
> Ruby support

- xslt_src/common.xsl
> common.xsl updated for fixing metanorma/metanorma-plateau#191

- xslt_src/itu.recommendation.core.xsl
> ITU xslt updated for metanorma/itu-contribution-samples#5

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> common.xsl updated for fixing missing formula num

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> common.xsl refactored for named destination, metanorma/mn2pdf#334

- xslt_src/common.xsl
> common.xsl updated for span class fmt-hi, metanorma/metanorma-ogc#798

- xslt_src/ogc.white-paper.core.xsl
> OGC white-paper xslt updated for tags structure

- xslt_src/common.xsl
- xslt_src/iho.standard.core.xsl
> IHO xslt updated for recommendation support, metanorma/metanorma-iho#325

- xslt_src/common.xsl
> common.xsl updated for table border styles, #859

- xslt_src/common.xsl
> common.xsl updated for metanorma/mn-samples-icc#30

- xslt_src/common.xsl
> common.xsl updated for metanorma/metanorma-standoc#1010

- xslt_src/bipm.brochure.core.xsl
> BIPM xslt updated for metanorma/iso-10303#561

- xslt_src/itu.recommendation.core.xsl
metanorma/itu-contribution-samples#5
> ITU xslt updated for cover page margins

- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> ISO title complementary support

- xslt_src/iso.international-standard.core.xsl
> Iso customize

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.xsl
metanorma/metanorma-standoc#995
> BIPM xslt updated for colophon, and baseline-shift style

- xslt_src/iho.standard.core.xsl
> IHO xslt updated for empty title fix, metanorma/metanorma-iho#365

- xslt_src/common.table.xsl
> common.table.xsl updated for borderless tables, plain 'true'

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for balance in participants table

- Makefile
- xslt_src/common.xsl
- xslt_src/iso.international-standard.core.xsl
> fox:title extension added, metanorma/mn2pdf#349

- xslt_src/ieee.standard.core.xsl
> IEEE xslt updated for two columns participants list

- .github/workflows/debian.yml
- xslt_src/common.bibitem.xsl
- xslt_src/common.note.xsl
> xslt updated for bibitem notes, #922

- xslt_src/common.bibitem.xsl
> common.bibitem.xsl fix, metanorma/metanorma-bsi#571

- xslt_src/common.toc.xsl
> IHO xslt updated for ToC list items indent, metanorma/metanorma-iho#395

- xslt_src/common.updatexml.xsl
- xslt_src/iho.standard.core.xsl
> floating title id issue fixing, #935

- xslt_src/common.bibitem.xsl
- xslt_src/common.p.xsl
- xslt_src/common.xsl
- xslt_src/ieee.standard.core.xsl
> Xslt ieee refactoring

- xslt_src/common.figure.xsl
- xslt_src/common.sourcecode.xsl
- xslt_src/common.table.xsl
- xslt_src/common.toc.xsl
- xslt_src/ribose.standard.core.xsl
> Ribose xslt update

- xslt_src/common.sourcecode.xsl
- xslt_src/common.updatexml.xsl
> Ribose xslt updated for URL identifiers, metanorma/metanorma-taste#24

- xslt_src/common.quote.xsl
> Plateau xslt updated for source indent, metanorma/metanorma-plateau#255

- xslt_src/jis.international-standard.core.xsl
- xslt_src/plateau.international-standard.core.xsl
metanorma/metanorma-plateau#255
> Plateau and JIS xslt updated for font in English text in fmt-link

- xslt_src/bipm.brochure.core.xsl
- xslt_src/cc.standard.core.xsl
- xslt_src/csa.standard.core.xsl
- xslt_src/iho.standard.core.xsl
- xslt_src/itu.recommendation.core.xsl
- xslt_src/ogc.standard.core.xsl
- xslt_src/ogc.white-paper.core.xsl
> XSLT updated, added empty template back-page, #879

- xslt_src/bipm.brochure.core.xsl
- xslt_src/common.boilerplate.xsl
- xslt_src/itu.recommendation.core.xsl
> xslt updated for statement styles, metanorma/mn-native-pdf#879

- xslt_src/ogc.standard.core.xsl
> OGC xslt updated for table, figure ToC, metanorma/metanorma-ogc#871

- xslt_src/common.bibitem.xsl
> common.bibitem.xsl updated for bibitem, metanorma/metanorma-pdfa#16
